spring:
  application:
    name: mcp
  main:
    banner-mode: off
    web-application-type: none
  ai:
    mcp:
      server:
        name: blog-stdio-mcp-server
        version: 1.0.0
        type: SYNC
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        enabled: true
logging:
  pattern:
    console:
  file:
    name: /Users/olivier/IdeaProjects/casestudy/logs/mcp-blog-stdio-server.log
models:
  config:
    dir: /Users/olivier/IdeaProjects/casestudy/http/src/main/config/
server:
  port: 8081